auth:
- auth_name: pkipsk
  auth_type: signed_headers
base_image: ubuntu_18_04_proxy_python_3_8
build_args:
- name: example_arg
  required_arg: false
  type: int
meta:
  author: Team Oblivious
  author_email: hello@oblivious.ai
  git: https://github.com/ObliviousAI/FastAPI-Enclave-Services.git
  version: 0.1.0
paths:
- access: example_role
  path: /hello/
  short_description: Hello world example
- access: example_role
  path: /outbound/
  short_description: Example to demonstrate allowlist urls
- access: example_role
  path: /psi/submit_list
  short_description: Submit CSV list for private set intersection
- access: example_role
  path: /psi/compare
  short_description: Get result for private set intersection
- access: example_role
  path: /yao/submit_value
  short_description: Submit value list for Yao's Millionaires Problem
- access: example_role
  path: /yao/compare
  short_description: Get result for Yao's Millionaires Problem
roles:
- role_auth: pkipsk
  role_cardinality: 2
  role_description: This is simply an example role for demonstration purposes
  role_name: example_role
traffic:
- name: inbound
  port: 80
